### ISSUE TITLE
Why is everything wrapped in async/await?

### ISSUE THREAD

**Issue by phated** [Tilican/gd-com#1]
Awesome library!  I just found it when looking into Godot's websocket stuff.  Is there a reason all of the methods are wrapped as `async`?  It looks like everything being done is synchronous.

Keep up the great work!

**Comment by Tilican** [comment]
Hi,

When i start to develop this library i make it synchronous, and when i start to send more than 60 packets per second, server just crash everytime ...
Asynchronous solve this issue and make it faster.

Thx 👍

**Comment by phated** [comment]
That's really interesting! I haven't been sending data that quickly do I didn't run into that issue.

I'll try to set up a reproduction project.
