### ISSUE TITLE
UDP packets being received in bursts

### ISSUE THREAD

**Issue by Sietseq** [Tilican/gd-com#29]
Hi, I am having troubles with UDP packets being received on my server. I send packets at a constant rate on the client but on the NodeJS server they were being received in bursts. The on Message event freezes up regularly and then keep going. 

Server code: https://pastebin.com/uZCmhdTC
Client code: https://pastebin.com/HeuuLuKH

OS: PopOS 20.04 LTS
Node version: 10.19.0
NPM version: 6.14.4

Thanks for any help, this has been bugging me a lot. And I feel like I must be making some stupid mistake.

**Comment by Tilican** [comment]
Hey @Sietseq,

I tried your code with NodeJS v10.24.1 and v16 LTS and It works very well :)
I also tried to spam with a timer at 0.001 and it works too, I don't have any bursts :∕

What's your gd-com version and your Godot version ? 
What is your system architecture? Here I am under linux in 64 bits and it works perfectly

![image](https://user-images.githubusercontent.com/10628316/147951977-c7c715ad-bc74-4493-b00c-8f75464b752a.png)

**Comment by Sietseq** [comment]
In the package file it says: "@gd-com/utils": "^4.1.2"
And my Godot version: v3.4.2
My system architecture is also 64 bits.

I just had reinstalled my OS because I was having some troubles getting some games working. But now I am having troubles making my games :/ . I was making a system that managed connections through heartbeats and this test was just to see where the problem was. I guess it must be something with my hardware.

**Comment by Sietseq** [comment]
To show you what happens: https://streamable.com/4sfhjr

**Comment by Sietseq** [comment]
Seems like gd-com isn't the issue from some more testing. Seems like the problem is somewhere in my computer. Sorry that this wasn't relevant.
