### ISSUE TITLE
Incorrect type when parsing Arrays

### ISSUE THREAD

**Issue by NitroRobotto** [Tilican/gd-com#30]
Hi!

I've been working with gd-com this past month and I recently found myself stumped. I'm trying to send an array of JSON over WS but the get_var() function from Godot 3.4.2 seems to be parsing it as the wrong type.

The type it's being recognized at seems to change according to the contents of the array itself.

Here's a (shortened) version of the code I'm running:

Node:
```js
const action = putU8(7)
const list = putVar([{'a':1},{'b':2},{'c':3}], TYPE.ARRAY)
const data = Buffer.concat([action, list])
ws.send(answer.data)
```
Godot:
```gdscript
var packet := _peer.get_packet()
var buffer := StreamPeerBuffer.new()
buffer.set_data_array(packet)
var action := buffer.get_u8()
match action:
	7:
		var list = buffer.get_var()
		# at this point, 'list' is parsed as null, a float, or an int, depending on the contents of the array
```

Considering that last detail, my guess would be that I'm either doing something wrong, or there's some mistake in the way the Array type is being formatted in @gd-com, leading to the type being incorrectly parsed.

**Comment by NitroRobotto** [comment]
After reviewing Godot's source code, it turns out that calling `get_var()` on Godot's Stream Peer Buffer internally calls `get_data()`.

To fix this issue and allow arrays or other objects to be retrieved with ``get_var()``, it needs to be prepended with the data length. Circling back to my original example, the fix would look like this:

```gdscript
const action = putU8(7)
const list = putVar([{'a':1},{'b':2},{'c':3}], TYPE.ARRAY)
const list_length = putU32(list.length)

const data = Buffer.concat([action, list_length, list])
ws.send(answer.data)
```

Should adding the length of the var be part of the putVar's default behavior?

**Comment by Tilican** [comment]
Hey @NitroRobotto,
This is because gd-com only serializes the object and does not include the additional data.
As indicated in the readme file, the size data must be added manually for a getVar to work ... :)

```javascript
const gdCom = require('@gd-com/utils')

const test1 = gdCom.putVar(8)

const lengthBuffer = Buffer.alloc(4)
lengthBuffer.writeUInt32LE(test1.length, 0)

const finalBuffer = Buffer.concat([lengthBuffer, test1])

console.log(finalBuffer)
```

Let me know if it works :)

**Comment by NitroRobotto** [comment]
Hey, thanks! Somehow after checking out the readme & examples a bunch of times, that obvious detail still slipped my mind.

Yes, it worked perfectly fine. Thanks for the work on gd-com!
