### ISSUE TITLE
Does the putString() function support multiple languages?

### ISSUE THREAD

**Issue by chenhanxue0831** [Tilican/gd-com#4]

**Comment by Tilican** [comment]
Hi,
With nodejs it's supported by default !
But for godot you have to do :
```python
var packet = ws.get_packet()
var buffer = StreamPeerBuffer.new()
buffer.set_data_array(packet)
print("I get %s !" % buffer.get_utf8_string())
```

NodeJs side : [source](https://glitch.com/edit/#!/gd-com-websocket-basic-string-test?path=server.js:19:0)
Godot console : 
![image](https://user-images.githubusercontent.com/10628316/55892068-f0487780-5bb5-11e9-99db-2d617c334239.png)

Enjoy

**Comment by chenhanxue0831** [comment]
thks u :)
