### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by elieobeid7** [Tilican/gd-com#6]
https://www.npmjs.com/package/gd-com

It says this package is deprecated. 

Really? Why? Is there an alternative? Why does it say so only on npmjs and not on github?

**Comment by Tilican** [comment]
Hey,
Read the deprecated message :)
The `gd-com` package is the really old implementation, it's better to install `@gd-com/utils`

Actually  `gd-com` and `@gd-com/utils` are the same, but all update going to be published on `@gd-com/utils`

**Comment by elieobeid7** [comment]
Ah so you can either install `gd-com` or `gd-com/utils` Wow I didn't know that you can actually install the first, thanks for letting me know.
