### ISSUE TITLE
get_var does not work properly

### ISSUE THREAD

**Issue by swarogan** [Tilican/gd-com#7]
When testet put/get only on nodejs, it's fork fine, but when test Your advanced example websocket, and change line 37 buffer.put_string('an extra parameter')
on buffer.put_var('an extra parameter') it return wrong data "♦  ↕   an extra parameter "

**Comment by Tilican** [comment]
Hi,
Carreful `put_var` and `put_string` are different !!

- `put_var` is for the `Variant` type of godot, there is 3 data : 
[4 => variant type](http://docs.godotengine.org/en/latest/tutorials/misc/binary_serialization_api.html#packet-specification)
String lenght
String itself

- `put_string` is for the `raw string` type of C++, there is only 2 data : 
String lenght
String itself

I use basic to send variant, and advanced to send custom raw packets

[websocket/advanced/client/WS.gd](https://github.com/gd-com/examples/blob/master/websocket/advanced/client/WS.gd#L37)

**Comment by Tilican** [comment]
I use advanced example to create custom raw packets and i don't use variant from godot

**Comment by swarogan** [comment]
works perfectly, thanks :)
